### ISSUE TITLE
Can't disable filter - ![original](image.jpg)

### ISSUE THREAD

**Issue by ulfben** [OleVik/grav-plugin-presentation-deckset#1]
The [Dockset documentation tells me](https://docs.deckset.com/English.lproj/Media/01-background-images.html) that I can remove the sickly blue highlight on background images by doing `![original](image.jpg)` instead of the plain `![](image.jpg)`

However, adding `original` in the square brackets causes the image to not render at all on the front-end. No data-background-image is being outputted at all.

(running Presentation v1.6.4 on Grav v1.6.3, and Presentation Deckset v1.1.4.)

**Comment by OleVik** [comment]
My [logic](https://github.com/OleVik/grav-plugin-presentation-deckset/blob/v1.1.4/API/DecksetParser.php#L304-L307) should see to that, I'll run some tests.

**Comment by OleVik** [comment]
This is fixed in the upcoming release.
