### ISSUE TITLE
During update Class 'Grav\Plugin\PresentationPlugin\API\Parser' not found

### ISSUE THREAD

**Issue by awrog** [OleVik/grav-plugin-presentation-deckset#4]
During last update I get an error:

[...]/public_html/user/plugins/presentation-deckset/classes/DecksetParser.php

     * @link       https://github.com/OleVik/grav-plugin-presentation
     */
     
    namespace Grav\Plugin\PresentationPlugin\API;
     
    use Grav\Common\Grav;
    use Grav\Common\Utils;
     
    /**
     * Deckset Parser API
     *
     * Deckset Parser API for parsing content
     *
     * @category Extensions
     * @package  Grav\Plugin\PresentationPlugin\API
     * @author   Ole Vik <git@olevik.net>
     * @license  http://www.opensource.org/licenses/mit-license.html MIT License
     * @link     https://github.com/OleVik/grav-plugin-presentation
     */
    class DecksetParser extends Parser implements ParserInterface
    {
        /**
         * Instantiate Parser API
         *
         * @param array     $config    Plugin configuration
         * @param Transport $transport Transport API
         */
        public function __construct($config, $transport)
        {
            $this->config = $config;
            $this->transport = $transport;
            // @deprecated 2.0.0
            $this->props = [];
        }
     
        /**
         * Regular expressions
         */
        const REGEX_SHORTCODES = '/\[\.(?<property>[a-zA-Z0-9_-]+)?:(?<value>.*)\]/mi';
        const REGEX_WORDS = '/^[a-zA-Z0-9_\- ]+/im';

Arguments

    "Class 'Grav\Plugin\PresentationPlugin\API\Parser' not found"

**Comment by OleVik** [comment]
I released [v1.3.2-beta.1](https://github.com/OleVik/grav-plugin-presentation-deckset/releases/tag/v1.3.2-beta.1) which should resolve this.

**Comment by OleVik** [comment]
Superceded by [v1.3.4](https://github.com/OleVik/grav-plugin-presentation-deckset/releases/tag/v1.3.4) which tries a simpler fix, hopefully not prone to the same errors.
