### ISSUE TITLE
How enable footer and slide numbers

### ISSUE THREAD

**Issue by badsonic** [OleVik/grav-plugin-presentation-deckset#5]
Hello

What is the best/easiest option to enable a footer with slide numbers and maybe a controller to enable/disable notes?

Thanks for these amazing plugins

**Comment by OleVik** [comment]
The footer has two approaches, either the [built-in template](https://github.com/OleVik/grav-plugin-presentation/blob/master/ADVANCED.md#changing-the-footer) or [through Reveal.js](https://github.com/hakimel/reveal.js/#slide-number). If you just want slide numbers, passing `slideNumber: true` to Reveal.js should work, eg.:

```yaml
options:
  slideNumber: true
```

In the plugin's options. For slide numbers, the latter approach is easiest. They can also work in conjunction, say, if you wanted to include a logo or title across all slides.

Notes do not have an explicit controller to enable or disable their rendering into HTML. However, they follow [Reveal.js' approach](https://github.com/hakimel/reveal.js/#speaker-notes) for whether to show them with the presentation; the `showNotes` query-parameter. If you are using the Admin-plugin, there are shortcuts when editing the presentation to open the various modes of viewing it.

**Comment by badsonic** [comment]
Thank you. The Reveal.js option works well. I'll try the second one as it gives more options.
